'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace UserControls
    
    Partial Public Class Contact
        
        '''<summary>
        '''phSendTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phSendTo As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''ddlSendTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlSendTo As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''phSendToText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phSendToText As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''litSendTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litSendTo As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''chkCC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCC As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
        
        '''<summary>
        '''phCreateHelpdeskTicket control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phCreateHelpdeskTicket As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''chkHelpdesk control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHelpdesk As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
        
        '''<summary>
        '''phReservation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phReservation As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''ddlReservations control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlReservations As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''txtSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSubject As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBody As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnSend control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSend As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''hypCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypCancel As Global.System.Web.UI.WebControls.HyperLink
        
        '''<summary>
        '''phErrorMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phErrorMessage As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''litErrorMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litErrorMessage As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''phSuccessMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phSuccessMessage As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''litSuccessMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litSuccessMessage As Global.System.Web.UI.WebControls.Literal
    End Class
End Namespace
