'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace UserControls

    Partial Public Class HelpdeskInfo

        '''<summary>
        '''hidHelpdeskInfoUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidHelpdeskInfoUrl As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidHelpdeskInfoMultiTool control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidHelpdeskInfoMultiTool As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidHelpdeskInfoResources control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidHelpdeskInfoResources As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    End Class
End Namespace
