'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace UserControls
    
    Partial Public Class ReservationView
        
        '''<summary>
        '''HelpdeskInfo1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HelpdeskInfo1 As Global.LabScheduler.UserControls.HelpdeskInfo
        
        '''<summary>
        '''divReservationView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divReservationView As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''phErrorMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phErrorMessage As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''litErrorMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litErrorMessage As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''tblSchedule control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblSchedule As Global.System.Web.UI.WebControls.Table
        
        '''<summary>
        '''trHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trHeader As Global.System.Web.UI.WebControls.TableRow
        
        '''<summary>
        '''tdHourRange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tdHourRange As Global.System.Web.UI.WebControls.TableCell
        
        '''<summary>
        '''hypHourRange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypHourRange As Global.System.Web.UI.WebControls.HyperLink
        
        '''<summary>
        '''Button1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''divStartConfirmationDialog control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divStartConfirmationDialog As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''litActiveReservationMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litActiveReservationMessage As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''btnConfirmOK control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnConfirmOK As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnConfirmCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnConfirmCancel As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''phNoData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phNoData As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''litNoData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litNoData As Global.System.Web.UI.WebControls.Literal
    End Class
End Namespace
