'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace UserControls

    Partial Public Class ResourceInfo

        '''<summary>
        '''hidResourceID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidResourceID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''rptResourceInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptResourceInfo As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace
