'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Pages
    
    Partial Public Class AdminProperties
        
        '''<summary>
        '''AdminTabMenu1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AdminTabMenu1 As Global.LNF.Web.Scheduler.Controls.AdminTabMenu
        
        '''<summary>
        '''litAlertMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAlertMessage As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''txtLateChargePenalty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLateChargePenalty As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtAuthExpWarning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAuthExpWarning As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtResourceIPPrefix control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtResourceIPPrefix As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ddlAdmin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAdmin As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAccount As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''dgKiosk control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgKiosk As Global.System.Web.UI.WebControls.DataGrid
        
        '''<summary>
        '''btnSubmit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
