'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Pages
    
    Partial Public Class AdminResources
        
        '''<summary>
        '''AdminTabMenu1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AdminTabMenu1 As Global.LabScheduler.UserControls.AdminTabMenu
        
        '''<summary>
        '''hidBaseUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidBaseUrl As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''hidAjaxUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidAjaxUrl As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''lblErrMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrMsg As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''pEditResource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pEditResource As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''hidResourceID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidResourceID As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''hidProcTechID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidProcTechID As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''hidLabID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidLabID As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''hidBuildingID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidBuildingID As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''lblAction control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAction As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtResourceID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtResourceID As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''rfv1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfv1 As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''txtResourceName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtResourceName As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''rfvResourceName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvResourceName As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''chkSchedulable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSchedulable As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''chkActive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkActive As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''txtDesc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDesc As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtHelpdeskEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHelpdeskEmail As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAdd As Global.System.Web.UI.HtmlControls.HtmlInputButton
        
        '''<summary>
        '''btnAddAnother control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAddAnother As Global.System.Web.UI.HtmlControls.HtmlInputButton
        
        '''<summary>
        '''btnUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUpdate As Global.System.Web.UI.HtmlControls.HtmlInputButton
        
        '''<summary>
        '''litToolEngineer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litToolEngineer As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''panResourceImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panResourceImage As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''imgPic control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgPic As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''litResourceImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litResourceImage As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''pListResource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pListResource As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''rptResources control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptResources As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace
