'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Pages
    
    Partial Public Class Lab
        
        '''<summary>
        '''litLabPath control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litLabPath As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litLabName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litLabName As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''lblDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDescription As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''imgPicture control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgPicture As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''phResourcesByProcTech control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phResourcesByProcTech As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''rptResourcesByProcTech control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptResourcesByProcTech As Global.System.Web.UI.WebControls.Repeater
        
        '''<summary>
        '''phResourcesByLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phResourcesByLocation As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''rptResourcesByLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptResourcesByLocation As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace
