'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Pages
    
    Partial Public Class Preference
        
        '''<summary>
        '''phErrorMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phErrorMessage As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''litErrorMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litErrorMessage As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''phSuccessMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phSuccessMessage As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''litSuccessMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litSuccessMessage As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''ddlBuilding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlBuilding As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlLab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlLab As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''rdoDefaultViewDay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoDefaultViewDay As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
        
        '''<summary>
        '''rdoDefaultViewWeek control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoDefaultViewWeek As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
        
        '''<summary>
        '''rdoHoursAllDay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoHoursAllDay As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
        
        '''<summary>
        '''rdoHoursRange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoHoursRange As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
        
        '''<summary>
        '''ddlBeginHour control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlBeginHour As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlEndHour control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlEndHour As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''chkWorkingDaysSun control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkWorkingDaysSun As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
        
        '''<summary>
        '''chkWorkingDaysMon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkWorkingDaysMon As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
        
        '''<summary>
        '''chkWorkingDaysTue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkWorkingDaysTue As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
        
        '''<summary>
        '''chkWorkingDaysWed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkWorkingDaysWed As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
        
        '''<summary>
        '''chkWorkingDaysThu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkWorkingDaysThu As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
        
        '''<summary>
        '''chkWorkingDaysFri control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkWorkingDaysFri As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
        
        '''<summary>
        '''chkWorkingDaysSat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkWorkingDaysSat As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
        
        '''<summary>
        '''chkShowTreeViewImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowTreeViewImages As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
        
        '''<summary>
        '''lblAccounts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAccounts As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblAccountsNames control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAccountsNames As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''hidAccountsResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidAccountsResult As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''chkCreateReserv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCreateReserv As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
        
        '''<summary>
        '''chkModifyReserv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkModifyReserv As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
        
        '''<summary>
        '''chkDeleteReserv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDeleteReserv As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
        
        '''<summary>
        '''chkInviteReserv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkInviteReserv As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
        
        '''<summary>
        '''dgResources control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgResources As Global.System.Web.UI.WebControls.DataGrid
        
        '''<summary>
        '''phResourcesNoData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phResourcesNoData As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''dgResourcePractice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgResourcePractice As Global.System.Web.UI.WebControls.DataGrid
        
        '''<summary>
        '''phResourcePracticeNoData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phResourcePracticeNoData As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''btnSubmit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
