'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Pages
    
    Partial Public Class ReservationCharges
        
        '''<summary>
        '''txtChargeMultiplier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtChargeMultiplier As Global.LabScheduler.NumericBox
        
        '''<summary>
        '''trLateCharge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trLateCharge As Global.System.Web.UI.HtmlControls.HtmlTableRow
        
        '''<summary>
        '''chkApplyLateChargePenalty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkApplyLateChargePenalty As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''btnSubmit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''lblErrMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrMsg As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
