'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Pages
    
    Partial Public Class Reservation
        
        '''<summary>
        '''hidMustAddInvitee control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidMustAddInvitee As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''litCreateModifyReservation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCreateModifyReservation As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''phReserve control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phReserve As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''litClientName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litClientName As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litStartDate As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''phPastSelectedDateWarning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phPastSelectedDateWarning As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''phStartTimeAndDuration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phStartTimeAndDuration As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''ddlStartTimeHour control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlStartTimeHour As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlStartTimeMin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlStartTimeMin As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''phDurationSelect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phDurationSelect As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''ddlDuration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlDuration As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''lblMaxSchedLimit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMaxSchedLimit As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''phDurationText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phDurationText As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''txtDuration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDuration As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''phIsRecurring control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phIsRecurring As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''chkIsRecurring control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsRecurring As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''chkKeepAlive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkKeepAlive As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
        
        '''<summary>
        '''chkAutoEnd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAutoEnd As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
        
        '''<summary>
        '''phActivity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phActivity As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''ddlActivity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlActivity As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''phActivityName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phActivityName As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''litActivityName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litActivityName As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''phActivityMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phActivityMessage As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''litActivityMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litActivityMessage As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''phBillingAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phBillingAccount As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''ddlAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAccount As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''phBillingAccountMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phBillingAccountMessage As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''litBillingAccountMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litBillingAccountMessage As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''txtNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNotes As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''phRecurringReservation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phRecurringReservation As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''rdoRecurringPatternWeekly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoRecurringPatternWeekly As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
        
        '''<summary>
        '''rdoRecurringPatternMonthly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoRecurringPatternMonthly As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
        
        '''<summary>
        '''rdoRecurringPatternWeeklySunday control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoRecurringPatternWeeklySunday As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
        
        '''<summary>
        '''rdoRecurringPatternWeeklyMonday control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoRecurringPatternWeeklyMonday As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
        
        '''<summary>
        '''rdoRecurringPatternWeeklyTuesday control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoRecurringPatternWeeklyTuesday As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
        
        '''<summary>
        '''rdoRecurringPatternWeeklyWednesday control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoRecurringPatternWeeklyWednesday As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
        
        '''<summary>
        '''rdoRecurringPatternWeeklyThursday control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoRecurringPatternWeeklyThursday As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
        
        '''<summary>
        '''rdoRecurringPatternWeeklyFriday control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoRecurringPatternWeeklyFriday As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
        
        '''<summary>
        '''rdoRecurringPatternWeeklySaturday control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoRecurringPatternWeeklySaturday As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
        
        '''<summary>
        '''ddlMonthly1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMonthly1 As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlMonthly2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMonthly2 As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''txtStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtStartDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''rdoRecurringRangeInfinite control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoRecurringRangeInfinite As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
        
        '''<summary>
        '''rdoRecurringRangeEndBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdoRecurringRangeEndBy As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
        
        '''<summary>
        '''txtEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEndDate As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''phProcessInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phProcessInfo As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''rptProcessInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptProcessInfo As Global.System.Web.UI.WebControls.Repeater
        
        '''<summary>
        '''hidProcessInfoData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidProcessInfoData As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''dgInvitees control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgInvitees As Global.System.Web.UI.WebControls.DataGrid
        
        '''<summary>
        '''phInviteeWarning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phInviteeWarning As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''litInviteeWarning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litInviteeWarning As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''btnSubmit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''litReservationAlert control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litReservationAlert As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''phConfirm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phConfirm As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''lblConfirm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblConfirm As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''phConfirmYesAndStart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phConfirmYesAndStart As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''btnConfirmYesAndStart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnConfirmYesAndStart As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnConfirmYes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnConfirmYes As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnConfirmNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnConfirmNo As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
