'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Pages
    
    Partial Public Class ReservationFacilityDownTime
        
        '''<summary>
        '''hidSelectedTabIndex control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidSelectedTabIndex As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''litAlert1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAlert1 As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''ddlLabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlLabs As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''odsLabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents odsLabs As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''lboxTools control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lboxTools As Global.System.Web.UI.WebControls.ListBox
        
        '''<summary>
        '''odsTool control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents odsTool As Global.System.Web.UI.WebControls.ObjectDataSource
        
        '''<summary>
        '''txtStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtStartDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ddlHour control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlHour As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlMin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMin As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlAMPM control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAMPM As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''txtEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEndDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ddlHourEnd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlHourEnd As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlMinEnd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMinEnd As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlAMPMEnd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAMPMEnd As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''txtNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNotes As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnReserve control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnReserve As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnBack As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''phGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phGrid As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''rptFDT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptFDT As Global.System.Web.UI.WebControls.Repeater
        
        '''<summary>
        '''hidDeleteGroupID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidDeleteGroupID As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''btnConfirmDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnConfirmDelete As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''phNoData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phNoData As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''phModify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phModify As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''hidGroupID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidGroupID As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''litName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litName As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''lboxModify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lboxModify As Global.System.Web.UI.WebControls.ListBox
        
        '''<summary>
        '''txtStartDateModify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtStartDateModify As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ddlHourModify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlHourModify As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlMinModify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMinModify As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlAMPMModify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAMPMModify As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''txtEndDateModify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEndDateModify As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ddlHourEndModify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlHourEndModify As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlMinEndModify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMinEndModify As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlAMPMEndModify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAMPMEndModify As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''txtNotesModify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNotesModify As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnUpdateModify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUpdateModify As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnBackModify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnBackModify As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''litAlert2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAlert2 As Global.System.Web.UI.WebControls.Literal
    End Class
End Namespace
