'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Pages
    
    Partial Public Class ReservationHistory
        
        '''<summary>
        '''ddlClients control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlClients As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlRange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlRange As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''txtStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtStartDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEndDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnSearchHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearchHistory As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''phSelectHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phSelectHistory As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''rptHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptHistory As Global.System.Web.UI.WebControls.Repeater
        
        '''<summary>
        '''litShowCanceledForModificationMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litShowCanceledForModificationMessage As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''phEditHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phEditHistory As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''phSaveAlert control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phSaveAlert As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''divSaveAlert control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divSaveAlert As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''litSaveAlertText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litSaveAlertText As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''phUpdateBilling control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phUpdateBilling As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''divUpdateBilling control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divUpdateBilling As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''litResourceName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litResourceName As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litReservationID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litReservationID As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litActivityName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litActivityName As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litIsStarted control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litIsStarted As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litIsCanceled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litIsCanceled As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litInvitees control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litInvitees As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litCurrentAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCurrentAccount As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''trAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trAccount As Global.System.Web.UI.HtmlControls.HtmlTableRow
        
        '''<summary>
        '''ddlEditReservationAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlEditReservationAccount As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''litEditReservationAccountMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litEditReservationAccountMessage As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litReservedBeginDateTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litReservedBeginDateTime As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litReservedEndDateTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litReservedEndDateTime As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litReservedRegularDuration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litReservedRegularDuration As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litActualBeginDateTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litActualBeginDateTime As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litActualEndDateTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litActualEndDateTime As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litActualRegularDuration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litActualRegularDuration As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litActualOvertimeDuration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litActualOvertimeDuration As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litChargeableBeginDateTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litChargeableBeginDateTime As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litChargeableEndDateTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litChargeableEndDateTime As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litChargeableRegularDuration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litChargeableRegularDuration As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litChargeableOvertimeDuration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litChargeableOvertimeDuration As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litForgiveAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litForgiveAmount As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''trForgiveForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trForgiveForm As Global.System.Web.UI.HtmlControls.HtmlTableRow
        
        '''<summary>
        '''txtForgiveAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtForgiveAmount As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNotes As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''chkEmailClient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEmailClient As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''litForgiveChargeNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litForgiveChargeNote As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''btnEditSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnEditSave As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnEditCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnEditCancel As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''litEditMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litEditMessage As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''litDebug control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litDebug As Global.System.Web.UI.WebControls.Literal
    End Class
End Namespace
