'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Pages
    
    Partial Public Class ResourceDayWeek
        
        '''<summary>
        '''ResourceTabMenu1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ResourceTabMenu1 As Global.LNF.Web.Scheduler.Controls.ResourceTabMenu
        
        '''<summary>
        '''phResourceToolTip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phResourceToolTip As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''panResourceToolTip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panResourceToolTip As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''litResourceToolTip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litResourceToolTip As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''ReservationView1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReservationView1 As Global.LabScheduler.UserControls.ReservationView
        
        '''<summary>
        '''txtCalendarURL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCalendarURL As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
