'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Pages
    
    Partial Public Class ResourceDocs
        
        '''<summary>
        '''ResourceTabMenu1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ResourceTabMenu1 As Global.LNF.Web.Scheduler.Controls.ResourceTabMenu
        
        '''<summary>
        '''phMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phMessage As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''dgDocs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgDocs As Global.System.Web.UI.WebControls.DataGrid
    End Class
End Namespace
