'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Pages
    
    Partial Public Class ResourceConfig
        
        '''<summary>
        '''ResourceTabMenu1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ResourceTabMenu1 As Global.LNF.Web.Scheduler.Controls.ResourceTabMenu
        
        '''<summary>
        '''hidResourceID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidResourceID As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''txtResourceName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtResourceName As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtAuthDuration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAuthDuration As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''chkAuthState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAuthState As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''txtFence control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFence As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ddlGranularity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlGranularity As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlOffset control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlOffset As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlMinReservTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMinReservTime As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlMaxReservation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMaxReservation As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''txtMaxSchedulable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaxSchedulable As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtMinCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMinCancel As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ddlGracePeriodHour control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlGracePeriodHour As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlGracePeriodMin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlGracePeriodMin As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''txtAutoEnd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAutoEnd As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtUnload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUnload As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''fileIcon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fileIcon As Global.System.Web.UI.HtmlControls.HtmlInputFile
        
        '''<summary>
        '''phIcon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phIcon As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''imgIcon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgIcon As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''txtDesc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDesc As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnSubmit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''phMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phMessage As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''phProcessInfoMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phProcessInfoMessage As Global.System.Web.UI.WebControls.PlaceHolder
        
        '''<summary>
        '''dgProcessInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgProcessInfo As Global.System.Web.UI.WebControls.DataGrid
    End Class
End Namespace
