'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Pages
    
    Partial Public Class UserRecurringReservation
        
        '''<summary>
        '''rptRecurringReservations control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptRecurringReservations As Global.System.Web.UI.WebControls.Repeater
        
        '''<summary>
        '''zgvRecurring control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents zgvRecurring As Global.System.Web.UI.WebControls.GridView
        
        '''<summary>
        '''fvRecurring control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fvRecurring As Global.System.Web.UI.WebControls.FormView
    End Class
End Namespace
